import type { AnalysisData } from '@/lib/types/api'

interface PrintMethodologyAppendixProps {
    analysis: AnalysisData
}

/**
 * Methodology Appendix — half-page section before the back cover.
 *
 * Surfaces only fields already visible elsewhere in the live app
 * (`companyUrl`, `industry`, plus a model + scoring-rubric reference
 * and an AI-disclosure paragraph). PE readers expect "show your work"
 * for AI-generated artifacts; this section is the credibility move.
 *
 * Always renders — even on analyses with sparse data — because the AI-
 * disclosure must accompany every PDF. The disclosure text is the
 * verbatim contract with the spec scenario in
 * `improve-pdf-export-content/specs/polished-pdf-export/spec.md`.
 */
const DISCLOSURE_TEXT =
    'This report is generated by AI analysis of public information. Findings should be verified before acting on them.'

const MODEL_REFERENCE = 'Generated by sc0red Advisory using a structured 6-step AI risk analysis pipeline.'
const SCORING_RUBRIC_REFERENCE =
    'Risk scores follow a 0–10 scale across eight standard categories (competitive displacement, technology obsolescence, talent & workforce, margin compression, customer behaviour, regulatory & compliance, supply chain & vendor, data & IP). Tier thresholds: 0–3 low, 4–6 moderate, 7–8 high, 9–10 critical.'

export default function PrintMethodologyAppendix({ analysis }: PrintMethodologyAppendixProps) {
    return (
        <section className="print-section print-section--break-before">
            <h2>Methodology</h2>

            <Block label="Subject">
                <div style={{ fontWeight: 600 }}>{analysis.companyName}</div>
                {analysis.companyUrl ? (
                    <div
                        style={{
                            fontSize: '0.85rem',
                            color: 'var(--text-secondary)',
                            wordBreak: 'break-all',
                        }}
                    >
                        {analysis.companyUrl}
                    </div>
                ) : null}
                {analysis.industry ? (
                    <div style={{ fontSize: '0.85rem', color: 'var(--text-secondary)' }}>
                        Industry: {analysis.industry}
                    </div>
                ) : null}
            </Block>

            <Block label="Model & Pipeline">
                <p style={{ margin: 0, fontSize: '0.85rem', lineHeight: 1.7 }}>{MODEL_REFERENCE}</p>
            </Block>

            <Block label="Scoring Rubric">
                <p style={{ margin: 0, fontSize: '0.85rem', lineHeight: 1.7 }}>{SCORING_RUBRIC_REFERENCE}</p>
            </Block>

            <Block label="AI Disclosure">
                <p
                    style={{
                        margin: 0,
                        fontSize: '0.85rem',
                        lineHeight: 1.7,
                        fontStyle: 'italic',
                        color: 'var(--text-secondary)',
                    }}
                >
                    {DISCLOSURE_TEXT}
                </p>
            </Block>
        </section>
    )
}

function Block({ label, children }: { label: string; children: React.ReactNode }) {
    return (
        <div style={{ marginBottom: '16px' }}>
            <div
                style={{
                    fontSize: '0.7rem',
                    fontWeight: 700,
                    color: 'var(--text-tertiary)',
                    textTransform: 'uppercase',
                    letterSpacing: '0.08em',
                    marginBottom: '6px',
                }}
            >
                {label}
            </div>
            {children}
        </div>
    )
}
