"""Tests for the Python PDF token signing implementation.

The Python module must produce byte-identical tokens to the canonical
TypeScript implementation at ``frontend/src/lib/pdf/token.ts`` (and its
byte-mirrored copy at ``backend/lambdas/pdf-render/src/token.ts``).
The Lambda's print route verifies tokens with the TS code; if Python
ever drifts, every async PDF export breaks.

These golden vectors were generated by running ``signToken`` from the
compiled Lambda module against fixed inputs (see commit-log for the
verification command). DO NOT update the expected values to match a
new Python output — instead, re-run the TS implementation and verify
both runtimes agree.
"""

from __future__ import annotations

import base64
import hashlib
import hmac
import json

import pytest

from src.utilities.pdf_token import TOKEN_TTL_SECONDS, sign_pdf_token


class TestSignPdfToken:
    def test_matches_typescript_golden_vector(self) -> None:
        # Golden vector: analysisId=a-1, orgId=org-1, secret=test-secret,
        # now=1700000000, ttl=60. Verified byte-identical to:
        #   node -e "const{signToken}=require('./dist/token.js');
        #     console.log(signToken({analysisId:'a-1',orgId:'org-1',
        #     nowSeconds:1700000000,ttlSeconds:60}, 'test-secret'));"
        expected = (
            "eyJhbmFseXNpc0lkIjoiYS0xIiwib3JnSWQiOiJvcmctMSIsImV4cCI6MTcwMDAwMDA2MH0"
            ".egKkAVpLkkVQXZgC-6eRFvk3OWoSs9T4LYsyRyRRmoU"
        )
        actual = sign_pdf_token(
            analysis_id="a-1",
            org_id="org-1",
            secret="test-secret",
            now_seconds=1700000000,
            ttl_seconds=60,
        )
        assert actual == expected

    def test_default_ttl_is_60_seconds(self) -> None:
        assert TOKEN_TTL_SECONDS == 60

    def test_payload_round_trips_to_expected_json(self) -> None:
        """Payload portion decodes to compact JSON with the right shape."""
        token = sign_pdf_token(
            analysis_id="a-2",
            org_id="org-2",
            secret="secret",
            now_seconds=1700000100,
            ttl_seconds=120,
        )
        encoded_payload = token.split(".", 1)[0]
        # base64url with no padding → re-add padding for stdlib decoding.
        padding = "=" * (-len(encoded_payload) % 4)
        decoded = base64.urlsafe_b64decode(encoded_payload + padding).decode("utf-8")
        assert json.loads(decoded) == {
            "analysisId": "a-2",
            "orgId": "org-2",
            "exp": 1700000220,  # now + ttl
        }

    def test_signature_validates_via_independent_hmac(self) -> None:
        """The signature is HMAC-SHA256(secret, base64url(payload))."""
        token = sign_pdf_token(
            analysis_id="a-3",
            org_id="org-3",
            secret="hmac-test-secret",
            now_seconds=1700000200,
        )
        encoded_payload, encoded_sig = token.split(".", 1)
        expected_sig_bytes = hmac.new(
            b"hmac-test-secret",
            encoded_payload.encode("ascii"),
            hashlib.sha256,
        ).digest()
        padding = "=" * (-len(encoded_sig) % 4)
        actual_sig_bytes = base64.urlsafe_b64decode(encoded_sig + padding)
        assert actual_sig_bytes == expected_sig_bytes

    def test_empty_secret_raises_value_error(self) -> None:
        with pytest.raises(ValueError, match="secret is required"):
            sign_pdf_token(analysis_id="a-1", org_id="org-1", secret="")

    def test_different_inputs_produce_different_signatures(self) -> None:
        """Tokens are scoped to (analysisId, orgId) — collisions would be a bug."""
        token_a = sign_pdf_token(
            analysis_id="a-1",
            org_id="org-1",
            secret="s",
            now_seconds=1700000000,
        )
        token_b = sign_pdf_token(
            analysis_id="a-2",
            org_id="org-1",
            secret="s",
            now_seconds=1700000000,
        )
        token_c = sign_pdf_token(
            analysis_id="a-1",
            org_id="org-2",
            secret="s",
            now_seconds=1700000000,
        )
        assert token_a != token_b
        assert token_a != token_c
        assert token_b != token_c
