type ScanProgress {
    scanId: String!
    companyId: String
    progress: Int!
    progressLabel: String!
    status: String!
}

type Mutation {
    publishProgress(input: ScanProgressInput!): ScanProgress
}

type Subscription {
    onScanProgress(scanId: String!): ScanProgress
        @aws_subscribe(mutations: ["publishProgress"])
}

input ScanProgressInput {
    scanId: String!
    companyId: String
    progress: Int!
    progressLabel: String!
    status: String!
}

schema {
    mutation: Mutation
    subscription: Subscription
}
