import { render, screen } from '@testing-library/react'
import { describe, it, expect } from 'vitest'

import PrintMethodologyAppendix from '@/components/print/PrintMethodologyAppendix'
import type { AnalysisData } from '@/lib/types/api'

const baseAnalysis: AnalysisData = {
    id: 'a-1',
    companyName: 'Test Co',
    companyUrl: 'https://test.example',
    industry: 'B2B SaaS',
    overallRiskScore: 5,
    riskTier: 'moderate',
    riskScores: [],
    opportunities: [],
}

describe('PrintMethodologyAppendix', () => {
    it('renders the section heading', () => {
        render(<PrintMethodologyAppendix analysis={baseAnalysis} />)
        expect(screen.getByText('Methodology')).toBeInTheDocument()
    })

    it('renders the company name and source URL', () => {
        render(<PrintMethodologyAppendix analysis={baseAnalysis} />)
        expect(screen.getByText('Test Co')).toBeInTheDocument()
        expect(screen.getByText('https://test.example')).toBeInTheDocument()
        expect(screen.getByText('Industry: B2B SaaS')).toBeInTheDocument()
    })

    it('omits the URL when companyUrl is missing', () => {
        render(<PrintMethodologyAppendix analysis={{ ...baseAnalysis, companyUrl: undefined }} />)
        expect(screen.queryByText('https://test.example')).not.toBeInTheDocument()
    })

    it('renders the AI-disclosure paragraph verbatim', () => {
        render(<PrintMethodologyAppendix analysis={baseAnalysis} />)
        expect(
            screen.getByText(
                'This report is generated by AI analysis of public information. Findings should be verified before acting on them.'
            )
        ).toBeInTheDocument()
    })

    it('renders the model and rubric sections', () => {
        render(<PrintMethodologyAppendix analysis={baseAnalysis} />)
        expect(screen.getByText('Model & Pipeline')).toBeInTheDocument()
        expect(screen.getByText('Scoring Rubric')).toBeInTheDocument()
        expect(screen.getByText(/sc0red Services using a structured 6-step/)).toBeInTheDocument()
        expect(screen.getByText(/0–10 scale across eight standard categories/)).toBeInTheDocument()
    })
})
