name: Reusable CI Checks

on:
  workflow_call:
    secrets:
      SONAR_TOKEN:
        required: false
      APP_ID:
        required: false
      APP_PRIVATE_KEY:
        required: false
      DEPLOY_KEY:
        required: false

jobs:
  lint:
    runs-on: ubuntu-latest
    name: Lint
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-python
        with:
          app-id: ${{ secrets.APP_ID }}
          app-private-key: ${{ secrets.APP_PRIVATE_KEY }}
          deploy-key: ${{ secrets.DEPLOY_KEY }}
      - name: Run lint
        run: make lint

  test:
    runs-on: ubuntu-latest
    name: Test
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-python
        with:
          app-id: ${{ secrets.APP_ID }}
          app-private-key: ${{ secrets.APP_PRIVATE_KEY }}
          deploy-key: ${{ secrets.DEPLOY_KEY }}
      - name: Run tests
        run: make test

  security:
    runs-on: ubuntu-latest
    name: Security
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-python
        with:
          app-id: ${{ secrets.APP_ID }}
          app-private-key: ${{ secrets.APP_PRIVATE_KEY }}
          deploy-key: ${{ secrets.DEPLOY_KEY }}
      - name: Run security checks
        run: make security
