name: Deploy Development

on:
  push:
    branches:
      - development
    paths:
      - 'backend/**'
      - 'infrastructure/**'
      - '.github/workflows/deploy-backend.yml'
      - '.github/workflows/_deploy.yml'

jobs:
  ci:
    name: CI Checks
    uses: ./.github/workflows/_ci-checks.yml
    secrets:
      DEPLOY_KEY: ${{ secrets.SIGNALFIELD_CORE_DEPLOY_KEY }}

  deploy:
    name: Staging
    needs: ci
    uses: ./.github/workflows/_deploy.yml
    with:
      environment: staging
      aws_prefix: DEV
    secrets:
      DEPLOY_KEY: ${{ secrets.SIGNALFIELD_CORE_DEPLOY_KEY }}
