name: Deploy Production

on:
  push:
    branches:
      - production
    paths:
      - 'backend/**'
      - 'infrastructure/**'
      - '.github/workflows/deploy-production.yml'
      - '.github/workflows/_deploy.yml'

jobs:
  ci:
    name: CI Checks
    uses: ./.github/workflows/_ci-checks.yml
    secrets:
      DEPLOY_KEY: ${{ secrets.SIGNALFIELD_CORE_DEPLOY_KEY }}

  deploy:
    name: Production
    needs: ci
    uses: ./.github/workflows/_deploy.yml
    with:
      environment: production
      aws_prefix: PROD
    secrets:
      DEPLOY_KEY: ${{ secrets.SIGNALFIELD_CORE_DEPLOY_KEY }}
