name: Deploy Testing

on:
  push:
    branches:
      - testing
    paths:
      - 'backend/**'
      - 'infrastructure/**'
      - '.github/workflows/deploy-testing.yml'
      - '.github/workflows/_deploy.yml'

jobs:
  ci:
    name: CI Checks
    uses: ./.github/workflows/_ci-checks.yml
    secrets:
      DEPLOY_KEY: ${{ secrets.SIGNALFIELD_CORE_DEPLOY_KEY }}

  deploy:
    name: Testing
    needs: ci
    uses: ./.github/workflows/_deploy.yml
    with:
      environment: testing
      aws_prefix: TEST
    secrets: inherit
