name: Deploy Testing

on:
  push:
    branches:
      - testing
    paths:
      - 'backend/**'
      - 'infrastructure/**'
      - '.github/workflows/deploy-testing.yml'
      - '.github/workflows/_deploy.yml'

jobs:
  ci:
    name: CI Checks
    uses: ./.github/workflows/_ci-checks.yml
    secrets:
      DEPLOY_KEY: ${{ secrets.SIGNALFIELD_CORE_DEPLOY_KEY }}

  deploy:
    name: Testing
    needs: ci
    uses: ./.github/workflows/_deploy.yml
    with:
      environment: testing
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.TEST_AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.TEST_AWS_SECRET_ACCESS_KEY }}
      AWS_ACCOUNT_ID: ${{ secrets.TEST_AWS_ACCOUNT_ID }}
      AWS_REGION: ${{ secrets.TEST_AWS_REGION }}
      DEPLOY_KEY: ${{ secrets.SIGNALFIELD_CORE_DEPLOY_KEY }}
      AMPLIFY_GITHUB_TOKEN: ${{ secrets.AMPLIFY_DEPLOYMENT }}
      NEXTAUTH_SECRET: ${{ secrets.NEXTAUTH_SECRET }}
      ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
      OPENAI_API_KEY: ${{ secrets.TEST_OPENAI_API_KEY }}
